[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "funlib.persistence"
version = "0.1"
authors = [
    {name = "William Patton", email = "pattonw@hhmi.org"},
    {name = "Jan Funke", email = "funkej@hhmi.org"},
]
description = "Interfaces for data (arrays and graphs) and storage formats (databases and file formats)"
readme = "README.rst"
requires-python = ">=3.7"
keywords = []
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "funlib.geometry",
    "daisy @ git+https://github.com/funkelab/daisy.git@master",
    "networkx",
    "zarr",
    "pymongo",
]