[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "funlib.persistence"
description = "Interfaces for data (arrays and graphs) and storage formats (databases and file formats)"
version = "0.1"
license = {text = "MIT"}
readme = "README.md"
authors = [
  {name = "William Patton", email = "pattonw@hhmi.org"},
  {name = "Jan Funke", email = "funkej@hhmi.org"},
]

requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
]
keywords = []

dependencies = [
  "funlib.geometry",
  "daisy @ git+https://github.com/funkelab/daisy.git@master",
  "networkx",
  "zarr",
  "pymongo",
  "numpy",
  'h5py',
]

[project.optional-dependencies]
dev = [
  'coverage>=5.0.3',
  'pytest',
  'black',
  'mypy',
]

[tool.black]
target_version = ['py36', 'py37', 'py38', 'py39', 'py310']
